[package]
name = "my_game"
version = "0.1.0"
edition = "2021"

[dependencies]
keycode = "0.4.0"
macroquad = { version = "0.4.13", features = ["audio"] }
quad-snd = "0.2.8"

[profile.dev.package.'*']
opt-level = 3
